### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by norrs** [thekua/Sample-Code#1]
From reading  https://www.thekua.com/atwork/2011/11/testing-logging-with-logback/ , which redirected me to https://github.com/thekua/Sample-Code/tree/master/java/logback-spike , it would be great to have a LICENSE file in this repository. 

Even tho you give the impression of it being public domain without concerns, it cannot be considered being public domain without explicit LICENSE saying so. 

Hereby request a LICENSE and I suggest using either BSD/MIT or something else.

I'd rather avoid having to "re-invent" the source and write this code over again and rather credit you and your blog post about the simple solution in our internal repositories. :-)

**Comment by thekua** [comment]
Sure. Added it in. Have fun!
